---
name: Build and deploy website

permissions:
  id-token: write
  contents: read

on  :
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: upload
        run: |
          sudo apt-get install ruby-full build-essential zlib1g-dev
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          gem install jekyll bundler
          npm install -g @azure/static-web-apps-cli

          cd jekyll
          jekyll build
          #sudo chmod -R 777 ~/work/benehaus_blog/benehaus_blog/jekyll/_site/_site/
          
          export SWA_CLI_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list --name webpageswa --query "properties.apiKey")
          swa deploy --env production
