name: Build and deploy Jekyll site to Azure Blob static page

on:
  push:
    branches:
      - '**'

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/jekyll/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        jekyll_src: 'jekyll'
        target_path: '_site'
    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: '_site'
        container_name: '$web'
        sas_token: ${{ secrets.sas_token }}
        account_name: ${{ secrets.storage_account_name }}
        overwrite: true
        sync: true