name: Build and deploy Jekyll site to Azure Blob static page

on:
  push:
    branches:
      - '**'

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    # Standard usage
    - uses: lemonarc/jekyll-action@1.0.0
    - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
      with:
        source_dir: '_site'
        container_name: $web
        sas_token: ${{ secrets.sas_token }}
        account_name: ${{ secrets.storage_account_name }} 
        extra_args: --overwrite True
        sync: true