name: Build and deploy Jekyll site to Azure Blob static page

on:
  push:
    branches:
      - 'main'

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/jekyll/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: helaili/jekyll-action@v2
      with:
        jekyll_src: '~/work/benehaus_blog/benehaus_blog/jekyll'
        target_path: '_site'
        build_dir: '_site'
        build_only: 'true'
    - name: ls
      run: ls ~/work/benehaus_blog/benehaus_blog/jekyll/_site/
    - uses: actions/upload-artifact@v3
      with:
        name: jekyll_site
        path: ~/work/benehaus_blog/benehaus_blog/_site/
    - uses: actions/download-artifact@v3
      with:
        name: jekyll_site
        path: ~/_site
    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
        cli_version: 2.34.1
        source_dir: ~/_site
        container_name: '$web'
        sas_token: ${{ secrets.SAS_TOKEN }}
        account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
        overwrite: 'true'