---
name: Build and deploy website and functions


on  :
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/jekyll/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:
          jekyll_src: jekyll
          target_path: _site
          build_dir: _site
          build_only: 'true'
      - name: chmod
        run: sudo chmod -R 777 ~/work/benehaus_blog/benehaus_blog/jekyll/_site/_site/
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          cli_version: 2.34.1
          source_dir: jekyll/_site/_site/
          container_name: $web
          sas_token: ${{ secrets.SAS_TOKEN }}
          account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          overwrite: 'true'
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az cdn endpoint purge -g benehaus-blog-rg -n benehausblogendpoint --profile-name benehaus-blog-cdn --content-paths '/*'
      - name: Resolve Project Dependencies Using Pip
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: behablogfunction
          package: .
          scm-do-build-during-deployment: true
          enable-oryx-build: true
